<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="fb_Distance" Id="{f403c34f-37c6-4d4c-830a-0fff24036bb1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK fb_Distance
VAR_INPUT
	POS1_X : LREAL;
	POS1_Y : LREAL;
	POS2_X : LREAL;
	POS2_Y : LREAL;
END_VAR
VAR_OUTPUT
	d : LREAL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[d := SQRT(EXPT((POS1_X-POS2_X),2) + EXPT((POS1_Y-POS2_Y),2));
]]></ST>
    </Implementation>
    <LineIds Name="fb_Distance">
      <LineId Id="3" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>